

services:
  # The FastAPI Backend Application
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - BACKEND_PATH_PLACEHOLDER:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/football_db
      - REDIS_URL=redis://redis_cache:6379
    depends_on:
      - db
      - redis_cache
    restart: on-failure

  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    ports:
      - "5432:5432" # Expose port for local inspection with a DB tool
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=football_db
    restart: on-failure

  # Redis Cache
  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379" # Expose port for local inspection
    restart: on-failure

volumes:
  postgres_data:
