version: '3.8'

services:
  backend:
    build: ./backend
    # container_name is removed
    ports:
      - "8000:8000"
    # The entire 'volumes' section is removed
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/football_db
      - REDIS_URL=redis://redis_cache:6379
    depends_on:
      - db
      - redis_cache
    restart: on-failure

  db:
    image: postgres:14-alpine
    # container_name is removed
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=football_db
    restart: on-failure

  redis_cache:
    image: redis:7-alpine
    # container_name is removed
    restart: on-failure

volumes:
  postgres_data:
